spring:
  datasource:
    url: ${PARKIO_DB_URL:jdbc:postgresql://localhost:5432/parkio}
    username: ${PARKIO_DB_USERNAME:postgres}
    password: ${PARKIO_DB_PASSWORD:123123}

  jpa:
    show-sql: ${PARKIO_JPA_SHOW_SQL:true}
