@startuml

package auth
package usuario
package rol
package estacionamiento
package cajon
package security
package common
package "shared.exception" as shared_exception
package config
package audit
package shared

auth --> security

usuario --> common
estacionamiento --> common
cajon --> common

rol --> shared_exception

security --> usuario

usuario --> shared
estacionamiento --> shared
cajon --> shared
rol --> shared

@enduml

/* Creacion de packages guia para cuando los haga

src/main/java/com/parkio
│
├── auth
│   ├── controller
│   ├── service
│   ├── dto
│   └── mapper
│
├── usuario
│   ├── controller
│   ├── service
│   ├── repository
│   ├── entity
│   ├── dto
│   └── mapper
│
├── rol
│   ├── controller
│   ├── dto
│   ├── entity
│   ├── mapper
│   ├── repository
│   └── service
│
├── estacionamiento
│   ├── controller
│   ├── service
│   ├── repository
│   ├── entity
│   ├── dto
│   └── mapper
│
├── cajon
│   ├── controller
│   ├── service
│   ├── repository
│   ├── entity
│   ├── dto
│   └── mapper
│
├── security
│   ├── filter
│   ├── service
│   └── config
│
├── common
│   ├── dto
│   ├── mapper
│   ├── constants
│   └── util
│
├── shared
│   ├── entity
│   └── exception
│
├── config
│
└── audit

*/
